# Add application configuration variables here, as shown below.
#
#SECRET_TOKEN: '20934820934823098'
#WEITLING_PASSWORD: 'tester'
#GMAIL_PASSWORD: 'tester'
#NEUE_APOTHEKE_PASEWALK_PASSWORD: 'tester'
#MY_SITE_SECRET: 'tester'
#MY_SITE_USERNAME: 'tester'